### ISSUE TITLE
add Gradio Web Demo for cvpr 2022 call for demos

### ISSUE THREAD

**Issue by AK391** [wangkai930418/ERD#1]
Hi, would you be interested in adding ERD to Hugging Face as a Gradio Web Demo for CVPR 2022 call for Demos? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

more info on CVPR call for demos: https://huggingface.co/CVPR

and here are guides for adding web demo to the organization

How to add a Space: https://huggingface.co/blog/gradio-spaces

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by wangkai930418** [comment]
Hi, it would be my pleasure to make a demo, but what I did in this project is related to incremental meta learning, I don't know how to make a fancy demo as you showed in your given links.
